In [13]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn import svm
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.linear_model import RidgeClassifierCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from numpy.random import shuffle

import warnings
warnings.filterwarnings("ignore")

In [18]:
data = pd.read_csv('https://raw.githubusercontent.com/koroteevmv/ML_course/main/ML4.1%20metrics/heart.csv')
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [ ]:
y = data["output"]
x = data.drop("output", axis=1)

logistic = LogisticRegression().fit(x, y)
logistic.score(x, y)

0.8547854785478548

In [ ]:
x_train, y_train = x[:200], y[:200]
x_train.shape, y_train.shape
x_test, y_test = x[200:], y[200:]
x_test.shape, y_test.shape

((103, 13), (103,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)
N = int(x.shape[0] * 0.8)

x_train, y_train, x_test, y_test = x[:N], y[:N], x[N:], y[N:]
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

(0.8884297520661157, 0.6229508196721312)

In [ ]:
data.tail()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0

In [ ]:
mask = np.array([True] * N + [False] * (y.shape[0] - N))
shuffle(mask)
mask

array([ True, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True,  True,

In [ ]:
x_train = x[mask]
x_train.shape
x_train, y_train, x_test, y_test = x[mask], y[mask], x[~mask], y[~mask]
x_train.shape, y_train.shape, x_test.shape, y_test.shape
logistic_test = LogisticRegression().fit(x_train, y_train)
logistic_test.score(x_train, y_train), logistic_test.score(x_test, y_test)

(0.8429752066115702, 0.8524590163934426)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [ ]:
y_test_pred = logistic_test.predict(x_test)
y_train_pred = logistic_test.predict(x_train)
confusion_matrix(y_train, y_train_pred)

array([[ 87,  25],
       [ 12, 118]])

In [ ]:
confusion_matrix(y_test, y_test_pred)

array([[21,  5],
       [ 5, 30]])

In [ ]:
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81        26
           1       0.86      0.86      0.86        35

    accuracy                           0.84        61
   macro avg       0.83      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



In [ ]:
precision_score(y_test, y_test_pred)

0.8571428571428571

In [ ]:
metrics = pd.DataFrame({
    "Train": [
        accuracy_score(y_train, y_train_pred),
        precision_score(y_train, y_train_pred),
        recall_score(y_train, y_train_pred),
        f1_score(y_train, y_train_pred),
    ],
    "Test": [
        accuracy_score(y_test, y_test_pred),
        precision_score(y_test, y_test_pred),
        recall_score(y_test, y_test_pred),
        f1_score(y_test, y_test_pred),
    ],
}, index = ["Accuracy", "Precision", "Recall", "F1"])

metrics

Train      Test
Accuracy   0.847107  0.836066
Precision  0.825175  0.857143
Recall     0.907692  0.857143
F1         0.864469  0.857143

# 1. Повторите анализ для других видов моделей. Используйте 5-10 разных классов моделей. Подсчитывайте только метрики на тестовой выборке.

In [19]:
y = data["output"]
x = data.drop("output", axis=1)
print(x)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

     age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  
0      0      1  
1      0      2

((242, 13), (242,), (61, 13), (61,))

In [20]:
def learning(x_train, y_train, x_test, y_test):
    models = [svm.SVC(),svm.SVC(kernel='linear'), svm.SVC(kernel='rbf'),
            svm.SVC(kernel='poly'),  KNeighborsClassifier(n_neighbors=4),
            MLPClassifier(), tree.DecisionTreeClassifier(max_depth=3),
            GaussianNB(), PassiveAggressiveClassifier(max_iter=1000),
            RidgeClassifierCV(alphas=[1e-3, 1e-2, 1e-1, 1]),
            RandomForestClassifier(max_depth=2, random_state=0),
            BaggingClassifier()]
    text = ["Метод опорных векторов (Без ядра)", "Метод опорных векторов (С линейным ядром)",
          "Метод опорных векторов (С гауссовым ядром)", "Метод опорных векторов (С полиномиальным ядром)",
          "Метод ближайших соседей", "Многослойный перцептрон", "Дерево решений", "Наивный байесовский классификатор",
          "Пассивно-агрессивный классификатор", "Гребневый классификатор", "Случайный лес", "Беггинг"]

    Accuracy = []
    Precision = []
    Recall = []
    F1 = []

    for i in models:
        i.fit(x_train, y_train)
        y_pred = i.predict(x_test)

        Accuracy.append(accuracy_score(y_test, y_pred))
        Precision.append(precision_score(y_test, y_pred))
        Recall.append(recall_score(y_test, y_pred))
        F1.append(f1_score(y_test, y_pred))
    return pd.DataFrame({"Models" : text, "Accuracy": Accuracy, "Precision":Precision, "Recall":Recall, "F1":F1})

learning(x_train, y_train, x_test, y_test)

Models  Accuracy  Precision  \
0                 Метод опорных векторов (Без ядра)  0.655738   0.631579   
1         Метод опорных векторов (С линейным ядром)  0.836066   0.769231   
2        Метод опорных векторов (С гауссовым ядром)  0.655738   0.631579   
3   Метод опорных векторов (С полиномиальным ядром)  0.655738   0.638889   
4                           Метод ближайших соседей  0.622951   0.666667   
5                           Многослойный перцептрон  0.786885   0.725000   
6                                    Дерево решений  0.770492   0.729730   
7                 Наивный байесовский классификатор  0.868852   0.848485   
8                Пассивно-агрессивный классификатор  0.491803   0.000000   
9                           Гребневый классификатор  0.836066   0.769231   
10                                    Случайный лес  0.836066   0.769231   
11                                          Беггинг  0.704918   0.685714   

      Recall        F1  
0   0.774194  0.695652  
1   0.967742  0.857143  
2   0.774194  0.695652  
3   0.741935  0.686567  
4   0.516129  0.581818  
5   0.935484  0.816901  
6   0.870968  0.794118  
7   0.903226  0.875000  
8   0.000000  0.000000  
9   0.967742  0.857143  
10  0.967742  0.857143  
11  0.774194  0.727273

Наивный байесовский метод показывает лучший результат.

# 2. Повторите анализ для другого датасета по вашему выбору. Используйте несколько моделей для сравнения. Используйте датасет для множественной классификации.

In [29]:
from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

iris = load_iris()
features = iris.data

data = pd.DataFrame(features, columns = iris.feature_names)
X = data.iloc[:, [0, 2]]
y = iris.target
X, y

(     sepal length (cm)  petal length (cm)
 0                  5.1                1.4
 1                  4.9                1.4
 2                  4.7                1.3
 3                  4.6                1.5
 4                  5.0                1.4
 ..                 ...                ...
 145                6.7                5.2
 146                6.3                5.0
 147                6.5                5.2
 148                6.2                5.4
 149                5.9                5.1
 
 [150 rows x 2 columns],
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2,

In [31]:
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((120, 2), (120,), (30, 2), (30,))

In [40]:
def learn(x_train, y_train, x_test, y_test):
    models = [svm.SVC(),svm.SVC(kernel='linear'), svm.SVC(kernel='rbf'),
            svm.SVC(kernel='poly'),  KNeighborsClassifier(n_neighbors=4),
            MLPClassifier(), tree.DecisionTreeClassifier(max_depth=3),
            GaussianNB(), PassiveAggressiveClassifier(max_iter=1000),
            RidgeClassifierCV(alphas=[1e-3, 1e-2, 1e-1, 1]),
            RandomForestClassifier(max_depth=2, random_state=0),
            BaggingClassifier()]
    text = ["Метод опорных векторов (Без ядра)", "Метод опорных векторов (С линейным ядром)",
          "Метод опорных векторов (С гауссовым ядром)", "Метод опорных векторов (С полиномиальным ядром)",
          "Метод ближайших соседей", "Многослойный перцептрон", "Дерево решений", "Наивный байесовский классификатор",
          "Пассивно-агрессивный классификатор", "Гребневый классификатор", "Случайный лес", "Беггинг"]

    Accuracy = []
    Precision = []
    Recall = []
    F1 = []

    for i, model in enumerate(models):
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        Accuracy.append(accuracy_score(y_test, y_pred))
        Precision.append(precision_score(y_test, y_pred, average = "micro"))
        Recall.append(recall_score(y_test, y_pred, average = "micro"))
        F1.append(f1_score(y_test, y_pred, average = "micro"))
    return pd.DataFrame({"Models" : text, "Accuracy": Accuracy, "Precision":Precision, "Recall":Recall, "F1":F1})

learn(x_train, y_train, x_test, y_test)

Models  Accuracy  Precision  \
0                 Метод опорных векторов (Без ядра)  0.966667   0.966667   
1         Метод опорных векторов (С линейным ядром)  0.966667   0.966667   
2        Метод опорных векторов (С гауссовым ядром)  0.966667   0.966667   
3   Метод опорных векторов (С полиномиальным ядром)  0.966667   0.966667   
4                           Метод ближайших соседей  0.966667   0.966667   
5                           Многослойный перцептрон  0.933333   0.933333   
6                                    Дерево решений  0.966667   0.966667   
7                 Наивный байесовский классификатор  0.933333   0.933333   
8                Пассивно-агрессивный классификатор  0.733333   0.733333   
9                           Гребневый классификатор  0.700000   0.700000   
10                                    Случайный лес  1.000000   1.000000   
11                                          Беггинг  0.933333   0.933333   

      Recall        F1  
0   0.966667  0.966667  
1   0.966667  0.966667  
2   0.966667  0.966667  
3   0.966667  0.966667  
4   0.966667  0.966667  
5   0.933333  0.933333  
6   0.966667  0.966667  
7   0.933333  0.933333  
8   0.733333  0.733333  
9   0.700000  0.700000  
10  1.000000  1.000000  
11  0.933333  0.933333

Лучший результат показывает 'Случайный лес'

# 3.Повторите анализ для датасета, предназначенного для решения задачи регрессии. Используйте все метрики качества регрессии, изученные на лекции. Постройте 5 - 10 разных моделей регрессии.

In [44]:
from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

iris = load_iris()
features = iris.data

data = pd.DataFrame(features, columns = iris.feature_names)
X = data.iloc[:, [0, 2]]
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((120, 2), (120,), (30, 2), (30,))

In [45]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor


from sklearn.metrics import explained_variance_score
from sklearn.metrics import max_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import pandas as pd


def learn1(X_train, y_train, X_test, y_test):
  models = {
      # 'SVR (linear)': SVR(kernel='linear'),
      'SVR (rbf)': SVR(kernel='rbf'),
      'SVR (poly)': SVR(kernel='poly'),
      'KNeighbors': KNeighborsRegressor(),
      'MLP': MLPRegressor(max_iter=1000),
      'DecisionTree': DecisionTreeRegressor(),
      'Ridge': Ridge(),
      'Lasso': Lasso(),
      'ElasticNet': ElasticNet(),
      'RandomForest': RandomForestRegressor(),
      'Bagging': BaggingRegressor()
  }

  evs = []
  max_er = []
  mae = []
  mse = []
  r2 = []


  for name, model in models.items():
      model.fit(X_train, y_train)

      y_pred = model.predict(X_test)

      evs.append(explained_variance_score(y_test, y_pred))
      max_er.append(max_error(y_test, y_pred))
      mae.append(mean_absolute_error(y_test, y_pred))
      mse.append(mean_squared_error(y_test, y_pred))
      r2.append(r2_score(y_test, y_pred))


  return pd.DataFrame({"Models" : models.keys(), "explained_variance_score": evs,
                       "max_error":max_er, "mean_absolute_error":mae, "mean_squared_error":mse, "r2_score":r2 })

learn1(x_train, y_train, x_test, y_test)

Models  explained_variance_score  max_error  mean_absolute_error  \
0     SVR (rbf)                  0.943427   0.547325             0.143074   
1    SVR (poly)                  0.912505   0.565819             0.201366   
2    KNeighbors                  0.971218   0.400000             0.060000   
3           MLP                  0.737701   0.925510             0.587523   
4  DecisionTree                  0.953526   1.000000             0.033333   
5         Ridge                  0.918520   0.504194             0.177118   
6         Lasso                  0.379187   0.851092             0.607525   
7    ElasticNet                  0.693843   0.735433             0.435774   
8  RandomForest                  0.975541   0.712500             0.034750   
9       Bagging                  0.969535   0.800000             0.030000   

   mean_squared_error  r2_score  
0            0.039254  0.943383  
1            0.060697  0.912456  
2            0.020000  0.971154  
3            0.413883  0.403054  
4            0.033333  0.951923  
5            0.056626  0.918328  
6            0.463694  0.331210  
7            0.222942  0.678448  
8            0.017639  0.974560  
9            0.021667  0.968750

Лучший результат показывает рандомный лес.